/**
 * Article pool organized by category.
 * Updated from CURRENT Monthly Cluster Analysis (Ahrefs) — June 2026.
 * Titles are derived from URL slugs for display; real titles are fetched
 * from the Innago site at generation time for Claude's prompt.
 */

function slugToTitle(url) {
  const slug = url.replace(/^https?:\/\/innago\.com\//, '').replace(/\/$/, '');
  return slug
    .replace(/-/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

export const CATEGORIES = {
  'Accounting & Finance': [
    'https://innago.com/accounting-best-practices-for-landlords/',
    'https://innago.com/9-tips-to-keep-good-financial-records-for-landlords/',
    'https://innago.com/landlords-and-tracking-rental-property-expenses-what-you-need-to-know/',
    'https://innago.com/7-reasons-to-have-separate-bank-accounts-for-your-rental-business/',
    'https://innago.com/4-reasons-to-hire-a-cpa-for-your-rental-business/',
    'https://innago.com/financial-metrics-landlords-should-track/',
    'https://innago.com/what-is-rent-roll-and-why-is-it-important/',
    'https://innago.com/rental-property-accounting-terms-you-need-to-know/',
    'https://innago.com/everything-you-need-to-know-about-accounting-as-a-landlord/',
    'https://innago.com/top-10-excel-templates-for-rental-property-finances/',
    'https://innago.com/whats-the-difference-between-cash-and-accrual-accounting/',
  ],

  'Leasing': [
    'https://innago.com/10-essential-lease-terms/',
    'https://innago.com/a-quick-guide-for-leasing-to-college-students/',
    'https://innago.com/adding-tenants-to-existing-lease/',
    'https://innago.com/altering-lease-mid-term/',
    'https://innago.com/comparing-commercial-lease-types-2/',
    'https://innago.com/different-ways-to-structure-late-fees/',
    'https://innago.com/electronic-signature-security/',
    'https://innago.com/electronic-signatures-vs-digital-signatures/',
    'https://innago.com/everything-you-need-to-know-about-leasing/',
    'https://innago.com/everything-you-need-to-know-about-writing-a-room-rental-agreement/',
    'https://innago.com/fixed-term-and-alternative-lease-structures/',
    'https://innago.com/grace-periods-and-late-fees/',
    'https://innago.com/handle-inherited-lease/',
    'https://innago.com/how-to-sign-a-lease-via-email/',
    'https://innago.com/individual-joint-leases/',
    'https://innago.com/lease-signing-etiquette-and-protocols/',
    'https://innago.com/making-the-most-of-your-online-lease/',
    'https://innago.com/month-to-month-lease-guide/',
    'https://innago.com/multi-year-lease/',
    'https://innago.com/online-leases-how-they-work/',
    'https://innago.com/online-leasing-myths-misconceptions/',
    'https://innago.com/overlooked-lease-items/',
    'https://innago.com/removing-tenant-wont-leave-after-lease-expires/',
    'https://innago.com/renters-insurance-require-tenants/',
    'https://innago.com/renters-paint/',
    'https://innago.com/requiring-lease-guarantor/',
    'https://innago.com/returning-the-security-deposit-common-concerns/',
    'https://innago.com/security-deposits-for-commercial-rentals/',
    'https://innago.com/security-deposits-how-much-to-charge/',
    'https://innago.com/signing-leases-online/',
    'https://innago.com/subleasing-good-bad/',
    'https://innago.com/things-to-consider-renewing-lease/',
    'https://innago.com/understanding-commercial-rental-fees/',
    'https://innago.com/understanding-lease-addenda/',
    'https://innago.com/using-plain-language-leases/',
    'https://innago.com/what-does-the-security-deposit-cover/',
  ],

  'Evictions': [
    'https://innago.com/how-to-evict-a-tenant/',
    'https://innago.com/what-is-the-cost-of-an-eviction/',
    'https://innago.com/6-legal-reasons-to-evict-a-tenant/',
    'https://innago.com/a-quick-guide-to-cash-for-keys/',
    'https://innago.com/how-to-prepare-for-an-eviction-court-hearing/',
    'https://innago.com/how-to-write-a-eviction-notice/',
    'https://innago.com/7-ways-to-avoid-evictions/',
    'https://innago.com/6-mistakes-landlords-make-during-evictions/',
    'https://innago.com/what-should-you-do-after-evicting-a-tenant/',
    'https://innago.com/everything-landlords-need-to-know-about-evictions/',
  ],

  'Tenant Screening': [
    'https://innago.com/benefits-screening-tenants/',
    'https://innago.com/tenant-scoring-system/',
    'https://innago.com/tenant-screening-guide/',
    'https://innago.com/how-to-screen-tenants/',
    'https://innago.com/social-media-tenant-screening/',
    'https://innago.com/passive-tenant-screening/',
    'https://innago.com/fair-housing-laws/',
    'https://innago.com/rental-application-information/',
    'https://innago.com/cost-skipping-tenant-screening/',
    'https://innago.com/understanding-background-checks/',
    'https://innago.com/hard-vs-soft-credit-inquiries/',
    'https://innago.com/interpreting-tenants-credit-report/',
    'https://innago.com/how-to-spot-fake-pay-stubs/',
    'https://innago.com/legal-reasons-to-deny-a-tenant-application/',
    'https://innago.com/best-tenant-screening-services-to-use-in-2024/',
    'https://innago.com/tenant-screening-laws-by-state/',
  ],

  'Rent Collection': [
    'https://innago.com/should-landlords-waive-late-fees/',
    'https://innago.com/calculating-prorated-rent/',
    'https://innago.com/landlords-should-not-use-paypal-venmo-collect-rent/',
    'https://innago.com/pros-and-cons-of-rent-payments-through-bank/',
    'https://innago.com/online-payments-enhance-transparency/',
    'https://innago.com/risks-cash-payments/',
    'https://innago.com/commercial-properties-online-payments/',
    'https://innago.com/real-cost-paper-check/',
    'https://innago.com/online-rent-payments-modern-renting/',
    'https://innago.com/why-accept-rent-by-credit-card/',
    'https://innago.com/mobile-rent-collection/',
    'https://innago.com/rent-payment-fraud/',
    'https://innago.com/legal-issues-regarding-rent-collection/',
    'https://innago.com/ach-payments/',
    'https://innago.com/8-myths-online-payments/',
    'https://innago.com/collect-rent-online/',
    'https://innago.com/online-rent-collection/',
    'https://innago.com/credit-card-chargebacks/',
    'https://innago.com/benefits-online-rent-collection/',
    'https://innago.com/everything-to-know-about-online-payments/',
    'https://innago.com/how-often-can-landlords-raise-rent/',
  ],

  'Maintenance': [
    'https://innago.com/preventative-rental-maintenance-2/',
    'https://innago.com/preventative-rental-maintenance-1/',
    'https://innago.com/free-property-maintenance-checklist/',
    'https://innago.com/everything-you-need-to-know-about-mold-inspections/',
    'https://innago.com/landlords-guide-to-normal-vs-excessive-wear-and-tear/',
    'https://innago.com/who-is-responsible-for-smoke-and-carbon-monoxide-detectors-at-a-rental-property/',
    'https://innago.com/when-to-replace-floors-5-signs-that-its-time-for-a-rental-flooring-update/',
    'https://innago.com/what-to-do-if-your-pipes-are-frozen/',
    'https://innago.com/piping-materials/',
    'https://innago.com/piping-ownership-and-responsibility/',
    'https://innago.com/plumbing-landscaping-and-repairs/',
    'https://innago.com/plumbing-potable-drinking-water/',
    'https://innago.com/tenant-plumbing-problems/',
    'https://innago.com/spring-cleaning-rental-property/',
    'https://innago.com/rental-property-snow-removal/',
    'https://innago.com/cleaning-appliances/',
    'https://innago.com/preserve-hardwood/',
    'https://innago.com/exterminator-tenant-landlord/',
    'https://innago.com/holiday-season-checklist/',
    'https://innago.com/how-to-get-rid-of-cigarette-smoke-odor-from-a-rental-unit/',
    'https://innago.com/12-landscaping-tips-for-winter/',
    'https://innago.com/apartment-mold-how-to-get-a-free-mold-inspection/',
    'https://innago.com/cooktops-vs-ranges-which-is-a-better-investment-for-your-rental/',
    'https://innago.com/what-is-a-certificate-of-occupancy-inspection/',
    'https://innago.com/what-is-a-natural-hazards-disclosure-report-and-what-should-real-estate-investors-know-about-it/',
    'https://innago.com/what-to-know-about-deep-cleaning-rental-property-carpets/',
    'https://innago.com/9-common-myths-about-tenant-screening/',
  ],

  'Property Management Software': [
    'https://innago.com/how-to-choose-the-right-property-management-software/',
    'https://innago.com/7-benefits-property-management-software-realtors/',
    'https://innago.com/choosing-rent-collection-software/',
    'https://innago.com/how-to-find-better-tenants-using-property-management-software/',
    'https://innago.com/manage-the-entire-rent-collection-process-with-property-management-software/',
    'https://innago.com/fill-units-quicker-with-property-management-software/',
    'https://innago.com/improve-tenant-communication-using-property-management-software/',
    'https://innago.com/how-to-streamline-the-lease-signing-process-using-property-management-software/',
    'https://innago.com/core-features-property-management-software/',
    'https://innago.com/secondary-features-property-management-software/',
    'https://innago.com/property-management-software-pricing-models/',
    'https://innago.com/how-to-use-reviews-when-comparing-property-management-software-options/',
    'https://innago.com/how-to-use-property-management-software-reduce-costs-save-time/',
    'https://innago.com/property-management-software-101-getting-setup/',
    'https://innago.com/efficient-growth/',
    'https://innago.com/what-does-property-management-really-cost-in-2023/',
    'https://innago.com/how-to-manage-condo-and-hoa-communities-with-property-management-software/',
    'https://innago.com/software-best-residential-property-management-software/',
    'https://innago.com/software-5-best-student-housing-property-management-software-in-2025/',
    'https://innago.com/software-best-commercial-property-management-software-in-2025/',
    'https://innago.com/best-self-storage-management-software/',
    'https://innago.com/software-what-is-property-management-software/',
    'https://innago.com/best-mobile-home-park-management-software-in-2025/',
    'https://innago.com/5-best-free-property-management-software-for-small-landlords-in-2025/',
    'https://innago.com/5-best-rent-collection-software-in-2025/',
  ],

  'Taxes': [
    'https://innago.com/the-basics-of-depreciation-for-landlords/',
    'https://innago.com/4-things-you-need-to-know-about-taxes-as-a-landlord/',
    'https://innago.com/an-overview-of-deductions-for-landlords/',
    'https://innago.com/what-landlords-need-to-know-about-taxes/',
    'https://innago.com/how-to-complete-1099s-as-a-landlord/',
    'https://innago.com/key-2026-tax-deadlines-checklist-for-landlords/',
    'https://innago.com/the-difference-between-repairs-and-improvements-on-your-taxes/',
    'https://innago.com/understanding-landlord-tax-classifications/',
    'https://innago.com/2-ways-to-maximize-your-depreciation-deduction/',
    'https://innago.com/how-to-maximize-the-pass-through-deduction/',
    'https://innago.com/how-to-calculate-depreciation/',
    'https://innago.com/natural-disasters-casualty-loss-rental-property/',
    'https://innago.com/sold-property-rental-property-taxes/',
    'https://innago.com/tax-shelters-and-considerations-for-real-estate-investors/',
    'https://innago.com/what-you-need-to-know-about-operating-expenses-for-tax-purposes/',
    'https://innago.com/what-you-should-know-about-cost-segregation-as-a-landlord/',
  ],

  'New Landlords': [
    'https://innago.com/10-steps-to-rent-home-2025/',
    'https://innago.com/how-to-start-a-property-management-company/',
    'https://innago.com/landlord-insurance-what-is-it-and-do-you-need-it/',
    'https://innago.com/the-best-websites-to-use-when-house-hunting/',
    'https://innago.com/types-of-nightmare-tenants-and-how-to-avoid-them/',
  ],

  'Increasing Revenue': [
    'https://innago.com/amenities-increase-revenue/',
    'https://innago.com/adding-fees-to-increase-revenue/',
    'https://innago.com/improve-property-to-increase-rent-price/',
    'https://innago.com/understanding-market-to-increase-rent-price/',
    'https://innago.com/ways-to-minimize-tenant-turnover/',
    'https://innago.com/increase-rent-property-value/',
    'https://innago.com/lower-financing-expenses/',
    'https://innago.com/monetize-land-maximize-revenue/',
    'https://innago.com/save-energy-costs/',
    'https://innago.com/7-important-fees/',
    'https://innago.com/tenant-turnover-cost/',
    'https://innago.com/increase-revenue-property/',
    'https://innago.com/renting-garage-space/',
    'https://innago.com/8-ways-landlords-lower-utility-costs/',
    'https://innago.com/reduce-rental-expenses-rental-properties/',
    'https://innago.com/high-tech-features-increase-rent-price/',
    'https://innago.com/self-managing-properties/',
    'https://innago.com/lower-tenant-turnover/',
    'https://innago.com/two-ways-improve-property-and-increase-revenue/',
    'https://innago.com/minimize-vacancy-time-on-rental-properties/',
    'https://innago.com/ways-landlords-can-add-revenue-streams/',
  ],

  'Rental Management': [
    'https://innago.com/tenant-communication-importance/',
    'https://innago.com/landlord-checklist-for-leasing-your-first-property/',
    'https://innago.com/essential-property-inspection-checklists-for-landlords/',
    'https://innago.com/what-landlords-need-to-know-about-squatters-rights/',
    'https://innago.com/a-complete-list-of-security-deposit-deductions/',
    'https://innago.com/5-reasons-to-centralize-your-real-estate-data/',
    'https://innago.com/furniture-left-behind/',
    'https://innago.com/if-tenants-do-not-place-utilities-in-their-names/',
    'https://innago.com/managing-utility-bill-payments/',
    'https://innago.com/landlord-tenant-friendship/',
    'https://innago.com/tenant-surveys-improve-business/',
    'https://innago.com/tenant-conflicts/',
    'https://innago.com/renting-to-elderly-tenants/',
    'https://innago.com/landlording-habits-2018/',
    'https://innago.com/silent-landlord-problems/',
    'https://innago.com/effective-late-fees/',
    'https://innago.com/long-term-guests/',
    'https://innago.com/moving-out-tenants/',
    'https://innago.com/late-fee-system-innago/',
    'https://innago.com/landlording-without-boundaries/',
    'https://innago.com/should-you-allow-early-move-out-inspections/',
    'https://innago.com/how-to-write-a-landlord-reference-letter-free-template/',
    'https://innago.com/what-to-know-before-installing-cameras-at-your-rental-property/',
    'https://innago.com/serial-squatters-how-to-avoid-and-remove-them/',
    'https://innago.com/what-does-quiet-enjoyment-mean-in-real-estate/',
    'https://innago.com/how-to-handle-tenant-harassment-as-a-landlord/',
    'https://innago.com/what-landlords-need-to-know-about-renting-furnished-homes/',
    'https://innago.com/the-best-property-management-blogs-that-every-landlord-should-follow/',
    'https://innago.com/rubs-utility-billing-v-s-submetering/',
    'https://innago.com/when-and-how-to-issue-a-notice-of-abandonment-as-a-landlord/',
    'https://innago.com/tenant-improvement-ti-in-real-estate/',
    'https://innago.com/the-common-areas-renters-most-want-and-how-to-maintain-them/',
    'https://innago.com/rent-concessions-and-discounts-and-how-they-affect-your-effective-rent/',
    'https://innago.com/what-to-do-if-someone-is-trespassing-on-your-property/',
    'https://innago.com/the-basics-of-triple-net-lease-agreements-nnn-for-landlords/',
  ],

  'Property Listings': [
    'https://innago.com/how-to-use-listing-syndication-software/',
    'https://innago.com/landlords-guide-to-rental-property-listings/',
    'https://innago.com/benefits-listing-syndication-software/',
    'https://innago.com/does-craigslist-work-rentals/',
    'https://innago.com/property-listings-personality/',
    'https://innago.com/create-the-perfect-craigslist-listing/',
    'https://innago.com/create-virtual-tour-for-rental-property/',
    'https://innago.com/10-ways-to-make-your-rental-listings-more-competitive/',
    'https://innago.com/best-rental-listing-sites-for-commercial-properties/',
    'https://innago.com/how-to-create-a-rental-listing/',
    'https://innago.com/best-listing-sites/',
    'https://innago.com/5-tips-better-virtual-tours-coronavirus/',
    'https://innago.com/how-to-create-the-perfect-property-listing/',
    'https://innago.com/perfect-rental-listing-photos/',
    'https://innago.com/what-are-the-pros-and-cons-of-an-exclusive-listing/',
    'https://innago.com/how-can-you-generate-property-management-leads/',
  ],

  'Real Estate Investing': [
    'https://innago.com/the-advantages-and-risks-of-1031-exchanges/',
    'https://innago.com/roi-for-rental-properties-and-why-it-matters/',
    'https://innago.com/the-brrrr-method-of-real-estate-investing/',
    'https://innago.com/cash-on-cash-return-how-and-why-to-calculate-it-for-real-estate/',
    'https://innago.com/best-types-of-real-estate-investments-for-2024/',
    'https://innago.com/why-you-should-start-investing-in-duplexes-and-triplexes/',
    'https://innago.com/top-5-most-landlord-friendly-states-to-invest-in/',
    'https://innago.com/4-creative-ways-to-invest-in-real-estate/',
    'https://innago.com/4-questions-landlord-insurance-agent-buying-rental-property/',
    'https://innago.com/opportunity-zones/',
    'https://innago.com/the-qualified-opportunity-zone-extension-act/',
    'https://innago.com/revamping-commercial-properties-new-use/',
    'https://innago.com/understanding-residential-commercial-real-estate-investing/',
    'https://innago.com/school-district-property-value/',
    'https://innago.com/downsize-property-portfolio/',
    'https://innago.com/networking-savvy-landlords/',
    'https://innago.com/backcasting-real-estate/',
    'https://innago.com/using-1-rule-expanding-portfolio/',
    'https://innago.com/rental-housing-portfolio-impact-covid-19/',
    'https://innago.com/new-tax-rule-affect-rental-business/',
    'https://innago.com/legal-checklist-buying-rental-property/',
    'https://innago.com/tips-and-strategies-for-evaluating-a-property/',
    'https://innago.com/complete-checklist-for-flipping-a-property/',
    'https://innago.com/how-to-close-on-a-distressed-property-in-2023/',
    'https://innago.com/how-to-estimate-roi-by-calculating-your-gross-rent-multiplier/',
    'https://innago.com/noi-what-real-estate-investors-need-to-know/',
    'https://innago.com/how-to-generate-passive-income-by-investing-in-mortgage-notes/',
    'https://innago.com/top-10-cities-for-real-estate-investing-in-2024/',
    'https://innago.com/2024-rental-market-forecast/',
    'https://innago.com/why-should-buyers-hire-a-realtor/',
    'https://innago.com/the-main-costs-of-buying-a-home-that-first-time-homebuyers-should-know/',
    'https://innago.com/the-5-best-cities-for-buying-condos-in-2024/',
    'https://innago.com/investing-in-condos-the-pros-and-cons/',
    'https://innago.com/investing-is-rent-outpacing-inflation/',
    'https://innago.com/the-difference-between-rent-stabilized-and-rent-controlled-housing-for-beginners/',
    'https://innago.com/dscr-loans-unlocking-cash-flow-based-financing-for-your-rentals-with-alex-bekeza/',
    'https://innago.com/3-things-to-know-about-amortization/',
    'https://innago.com/what-to-know-about-appraisals-and-appraisal-contingencies/',
    'https://innago.com/what-to-know-about-economic-obsolescence-and-appraised-value-in-real-estate/',
    'https://innago.com/the-as-is-condition-in-real-estate/',
    'https://innago.com/4-things-to-know-about-assumable-mortgages/',
    'https://innago.com/the-basics-of-backup-offers/',
    'https://innago.com/balloon-mortgages-101-what-are-the-pros-and-cons/',
    'https://innago.com/what-is-the-importance-of-a-bill-of-sale-in-real-estate/',
    'https://innago.com/blanket-mortgages-what-you-need-to-know/',
    'https://innago.com/tips-and-considerations-for-utilizing-bridge-loans/',
    'https://innago.com/types-of-real-estate-to-invest-in-brownstones-condominiums-duplexes-and-triplexes/',
    'https://innago.com/comparative-market-analysis-in-real-estate-using-comparables/',
    'https://innago.com/co-applicants-and-their-role-in-real-estate/',
    'https://innago.com/what-borrowers-should-know-about-buydown-mortgages/',
    'https://innago.com/the-significance-of-a-certificate-of-occupancy/',
    'https://innago.com/what-buyers-need-to-know-about-closing-costs/',
    'https://innago.com/understanding-your-debt-to-income-ratio-and-how-to-manage-it/',
    'https://innago.com/what-are-promissory-notes-and-deeds-of-reconveyance-in-real-estate/',
    'https://innago.com/representation-options-in-a-real-estate-transaction-fsbo-dual-agency-and-more/',
    'https://innago.com/what-does-earnest-money-mean-when-closing-on-a-house/',
    'https://innago.com/what-is-an-easement-in-real-estate/',
    'https://innago.com/eminent-domain-in-real-estate/',
    'https://innago.com/encroachment-in-real-estate/',
    'https://innago.com/significance-of-the-equal-credit-opportunity-act-in-real-estate/',
    'https://innago.com/navigating-equity-in-real-estate-investments/',
    'https://innago.com/tips-for-closing-on-your-home/',
    'https://innago.com/the-intricacies-of-escrow-and-per-diem-for-real-estate-investors/',
    'https://innago.com/fair-market-value-what-do-homeowners-need-to-know-and-how-do-you-calculate-it/',
    'https://innago.com/fannie-mae-and-freddie-mac-in-real-estate/',
    'https://innago.com/essential-information-about-fha-loans/',
    'https://innago.com/recognizing-functional-obsolescence-in-real-estate/',
    'https://innago.com/what-is-a-land-lease-agreement/',
    'https://innago.com/everything-you-need-to-know-about-good-faith-estimates-for-reverse-mortgages/',
    'https://innago.com/what-do-homeowners-need-to-know-about-homeowners-insurance/',
    'https://innago.com/what-is-a-second-mortgage-loan-in-real-estate/',
    'https://innago.com/what-you-need-to-know-about-home-sale-contingencies/',
    'https://innago.com/home-warranties-in-real-estate/',
    'https://innago.com/everything-real-estate-investors-need-to-know-about-ibuyers/',
    'https://innago.com/the-ins-and-outs-of-usda-and-va-loans/',
    'https://innago.com/what-does-it-mean-when-youre-under-contract-in-a-home-sale/',
    'https://innago.com/real-estate-laws-the-real-estate-settlement-procedures-act-and-truth-in-lending-act/',
    'https://innago.com/what-is-workforce-housing/',
    'https://innago.com/what-is-loss-mitigation-and-what-does-it-mean-for-real-estate-investors/',
    'https://innago.com/key-components-in-your-home-buying-journey/',
    'https://innago.com/what-new-buyers-should-know-about-mortgages/',
    'https://innago.com/piti-private-mortgage-insurance-and-rate-lock-what-do-real-estate-investors-need-to-know/',
    'https://innago.com/what-are-probate-sales-and-quitclaim-deeds/',
    'https://innago.com/the-right-of-first-refusal-clause-in-real-estate/',
    'https://innago.com/sellers-disclosure-and-net-sheets-two-essential-documents-when-buying-or-selling-homes/',
    'https://innago.com/overview-of-title-companies-and-title-insurance/',
    'https://innago.com/understanding-abstract-of-title-in-real-estate/',
    'https://innago.com/what-is-the-importance-of-a-bill-of-sale-in-real-estate/',
  ],

  'Pets': [
    'https://innago.com/service-emotional-support-animals-rental/',
    'https://innago.com/how-to-pet-proof-your-rental-property/',
    'https://innago.com/guide-renting-tenants-pets-2/',
    'https://innago.com/allow-tenants-pets/',
    'https://innago.com/allowing-exotic-animals-in-your-rental-properties/',
    'https://innago.com/difference-between-pet-fees-pet-deposit-pet-rent/',
    'https://innago.com/everything-you-need-to-know-about-pets-in-rental-properties/',
    'https://innago.com/pet-policies-why-you-need-one-and-what-to-include/',
    'https://innago.com/understanding-landlord-obligations-for-service-animals/',
    'https://innago.com/renters-insurance-and-pets/',
    'https://innago.com/how-to-handle-tenants-with-unauthorized-pets/',
    'https://innago.com/do-landlords-need-to-start-pet-screening/',
    'https://innago.com/what-pet-liability-issues-can-a-landlord-face/',
    'https://innago.com/how-to-design-your-rental-unit-to-be-more-pet-friendly/',
    'https://innago.com/a-state-by-state-breakdown-of-pet-deposit-laws/',
    'https://innago.com/how-to-handle-pet-related-complaints/',
    'https://innago.com/how-to-spot-esa-fraud-as-a-landlord/',
    'https://innago.com/advantages-and-disadvantages-of-renting-to-pet-owners/',
    'https://innago.com/pets-a-beginners-guide-to-the-pet-screening-process/',
  ],

  'Section 8 / Affordable Housing': [
    'https://innago.com/how-to-become-a-section-8-housing-landlord/',
    'https://innago.com/the-advantages-and-risks-of-becoming-a-section-8-landlord/',
    'https://innago.com/8-myths-about-renting-to-section-8-tenants/',
    'https://innago.com/how-to-screen-section-8-tenants/',
    'https://innago.com/how-to-evict-a-section-8-tenant/',
    'https://innago.com/what-is-affordable-housing-what-options-do-people-currently-have/',
    'https://innago.com/section-8-terms-to-know/',
    'https://innago.com/who-is-eligible-for-section-8-housing/',
    'https://innago.com/what-is-the-difference-between-section-8-and-public-housing/',
    'https://innago.com/landlords-most-frequently-asked-questions-about-housing-vouchers/',
    'https://innago.com/how-to-get-a-property-section-8-approved/',
    'https://innago.com/how-does-section-8-housing-work-for-tenants/',
    'https://innago.com/the-5-main-responsibilities-of-a-section-8-landlord/',
    'https://innago.com/understanding-section-8-fair-market-rent/',
    'https://innago.com/where-and-how-to-market-your-section-8-rentals/',
    'https://innago.com/everything-you-need-to-know-about-section-8-affordable-housing/',
  ],
};

/** Flat array of all articles with category label */
export const ALL_ARTICLES = Object.entries(CATEGORIES).flatMap(([category, urls]) =>
  urls.map((url) => ({
    url,
    category,
    slug: url.replace(/^https?:\/\/innago\.com\//, '').replace(/\/$/, ''),
    displayTitle: slugToTitle(url),
  }))
);

/** Pick articles for a schedule, rotating through categories */
export function pickArticlesForSchedule(slots, selectedCategories = null) {
  const pool = selectedCategories
    ? ALL_ARTICLES.filter((a) => selectedCategories.includes(a.category))
    : ALL_ARTICLES;

  if (pool.length === 0) return slots.map((s, i) => ({ ...s, article: ALL_ARTICLES[i % ALL_ARTICLES.length] }));

  const seed = new Date().toISOString().slice(0, 10);
  const shuffled = [...pool].sort((a, b) => {
    const ha = hashCode(a.url + seed);
    const hb = hashCode(b.url + seed);
    return ha - hb;
  });

  return slots.map((slot, i) => ({
    ...slot,
    article: shuffled[i % shuffled.length],
  }));
}

function hashCode(str) {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = (Math.imul(31, hash) + str.charCodeAt(i)) | 0;
  }
  return hash;
}
